### PR TITLE
Update comet.es_ES.po

### PR DESCRIPTION
**Pull request by donlaiq**
First 2000 rows (without proofreading).

### CODE REVIEW

**Comment by mason-cometbackup** [comment]
Hi @donlaiq , thank you so much for your efforts here, this is really fantastic work.

It looks like you've completed all the untranslated text.

Is there anything more you want to change, or are you complete?

If so, we can apply your changes into the next version of Comet (probably 24.8.0 in late August),

Best regards, 
Mason

**Comment by donlaiq** [comment]
Hi Mason,

Nice to e-meet you!

I have a few questions, maybe you can answer them:

197: What's an "error retry"? The same error appearing again and again?
362, 4901: In "path=%s", is 'path' part of the placeholder, or should I
translate it?
4501: Could you provide a sentence with the placeholders replaced?
5955: Self-Backup would be the same as Self-Service Backup?
6028: I shouldn't translate CONFIRM, otherwise the function checking for it
won't work, right?
8710: Could you give me some more context? Would it be something like "1
time", "2 times", "3 times", etc.?

Best,
donlaiq.

**Comment by mason-cometbackup** [comment]
Those are extremely good questions, thank you for asking!

---

> > `msgid "'If the last job encountered an error retry' setting on backup schedules"`
>
> 197: What's an "error retry"? The same error appearing again and again?

There's a setting elsewhere named "If the last job encountered an error, retry __ time(s)". This text here is about setting the default value for that other setting.

I think the fully correct English grammar would use a comma, probably it should have read like "error, retry". The intention is that "error" is a noun and "retry" is a verb.

---

> > `msgid "Access to file %s (path=%s) failed (%d: %s), skipping..."`
> > 
> > `msgid "Microsoft detected malware within file %s (path=%s), skipping..."`
> 
> 362, 4901: In "path=%s", is 'path' part of the placeholder, or should I translate it?

It's not part of the placeholder, please translate it.

---

> > msgid "Last reported backup job started %s and ended %s with status of '%s'"
>
> 4501: Could you provide a sentence with the placeholders replaced?

The first two placeholders are dates, and the last placeholder is something like "Success" or "Warning". I think the fully correct grammar would be if this sentence instead said `started at %s and ended at %s`.

An example would be: `Last reported backup job started 2024-08-16 00:00 and ended 2024-08-16 02:00 with status of 'Success'`

---

> > `msgid "Please ensure that you have taken a Server Self-Backup before performing this operation."`
>
> 5955: Self-Backup would be the same as Self-Service Backup?

"Self-Backup" is actually the name of a feature in Comet Server. It's where the Comet Server takes a backup of it's own self. If possible, can you make this match with the existing translation line 7352 `msgid "Server Self-Backup"` ?

The following translations around there (e.g. 7355, 7358) could also be used as examples, where "Server Self-Backup" is a noun.

We'll add a comment here to make this clear in the future.

---

> > `msgid "Please type CONFIRM to indicate that you understand: "`
>
> 6028: I shouldn't translate CONFIRM, otherwise the function checking for it won't work, right?

That's correct, please leave it as `CONFIRM` in english. In the future, we may change this to a placeholder `%s`, but if the Spanish text simply says `CONFIRM` then that's a change we can make ourselves.

---

> > `msgid "time(s)"`
>
> 8710: Could you give me some more context? Would it be something like "1 time", "2 times", "3 times", etc.?

That's correct, like "3 times". In the Comet app interface, there is a number input to the left of this text, where the user can choose a number such as 1, 2 or 3.

**Comment by donlaiq** [comment]
Thanks, Mason!

I think it's ready now!

**Comment by mason-cometbackup** [comment]
Hi @donlaiq - these translations are now publicly included in our latest Comet 24.6.10 Voyager release. Please check it out.

Thanks again for your contribution! If you have any more updates, we are happy to accept them anytime.

**Comment by donlaiq** [comment]
Hey @mason-cometbackup,
May I run this Comet 24.6.10 Voyager release from some of these public repositories: https://github.com/orgs/CometBackup/repositories ?
It would be a good exercise for me to start familiarizing myself with the source code before you hire me, 😁, because if all the things mentioned about the company on Comet's blog are true, then it is the company I would like to work for.
In any case, to evaluate it properly, I would at least need some screenshots to gain a better understanding of the running application.

**Comment by mason-cometbackup** [comment]
Thank you for your kind words 😄 It is nice to work here! We don't currently have any open hiring positions, but we do so often, so perhaps keep an eye on our LinkedIn page at https://www.linkedin.com/company/cometbackup/ for announcements.

The main Comet Backup product is closed-source, the GitHub repositories are only for our auxiliary things like translations and SDKs. If you want to try out the app, you can sign up at the main cometbackup.com website - if you use your same GitHub email, I'll give your account lots of free-trial credit.

By the way, here are some screenshots of the app in Spanish:

---

image

image

image

image

image

image

**Comment by donlaiq** [comment]
Thanks Mason, but I usually forget to review these kinds of announcements. If you believe I could be a valuable asset to the team or if you have any other questions about me, please feel free to reach out. You can find my email address on my GitHub profile.
Based on my research, Go appears to be the primary language in your technology stack. I can confidently say (with genuine humility 😏) that I am the best Go programmer in town 😎. 

By the way, I’ve opened a new pull request with the changes based on the screenshots I reviewed:
- It seems you already have the translated strings, but the buttons "Back", "Next" and "Cancel" are still in English
- In the last screenshot, there's still a sentence in English "Please ask an administrator to change this text" -> "Por favor, para cambiar este texto comuníquese con un administrador"

**Pull request merged**
